defaults:
  - encoder: clip_full
  - loss: contrastive_loss

_target_: model.Model

optimizer:
  _target_: torch.optim.AdamW
  # Must be partial to allow for the parameters to be passed in.
  _partial_: true
  lr: 0.00001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # Must be partial to allow for the optimizer to be passed in.
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

data_dir: ${paths.data_dir}

# compile model for faster training with pytorch 2.0
compile: True
