defaults:
  - encoder: clip_medgeese
  - loss: contrastive_loss

_target_: model.Model

optimizer:
  _target_: torch.optim.Adam
  # Must be partial to allow for the parameters to be passed in.
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # Must be partial to allow for the optimizer to be passed in.
  _partial_: true 
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with pytorch 2.0
compile: false
